import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import AboutUs from "../components/AboutUs";
import ContactUs from "../components/ContactUs";
import Footer from "../components/Footer";
import Landing from "../components/Landing";
import WorkTime from "../components/WorkTime";
import { useDispatch } from "react-redux";
import { PuplishServ } from "../slices/Services";

export default function Home(services) {
  const dispatch = useDispatch();

  dispatch(PuplishServ({ serv: services }));
  return (
    <div>
      <Head>
        <title>Rocky Студия </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/registered.png" />
      </Head>

      <main>
        {/* landing */}
        <Landing />
        {/* about us  */}
        <AboutUs />

        {/* workTime */}
        <WorkTime />

        {/* contact-us */}
        <ContactUs />
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const allData = await axios.get(
    `${process.env.NEXT_PUBLIC_URL}/api/v1/services`
  );

  return {
    props: {
      services: allData.data.allServices,
    },
  };
};
